
INSERT INTO TP.USERS SELECT USER_ID, USERNAME, CREATED, ACCOUNT_STATUS FROM DBA_USERS;
INSERT INTO TP.TABLESPACES( name, status) SELECT TABLESPACE_NAME, STATUS FROM DBA_TABLESPACES;
INSERT INTO TP.DATAFILES SELECT FILE_ID, FILE_NAME, BYTES, STATUS, TABLESPACE_NAME FROM DBA_DATA_FILES;
INSERT INTO TP.STATS SELECT STAT_ID, STAT_NAME, VALUE FROM dba_hist_osstat WHERE STAT_NAME = 'NUM_CPUS' and ROWNUM = 1;
INSERT INTO TP.STATS SELECT STAT_ID, STAT_NAME, VALUE FROM dba_hist_osstat WHERE STAT_NAME = 'NUM_CPU_CORES' and ROWNUM = 1;
INSERT INTO TP.STATS SELECT STAT_ID, STAT_NAME, VALUE FROM dba_hist_osstat WHERE STAT_NAME = 'NUM_CPU_SOCKETS' and ROWNUM = 1;
INSERT INTO TP.SESSIONS SELECT SID,USERNAME,MACHINE,STATUS,PROGRAM,TYPE,SCHEMANAME FROM V$SESSION;